### PR TITLE
Closes #1

### LINKED ISSUE #1: Validate color from System.Drawing.ColorTranslator.FromHtml
This:

````csharp
System.Drawing.ColorTranslator.FromHtml("wrong color");
````

Will be marked as an `Error`. Category is `Usage`.
Diagnostic id is `CC0053`

How to implement it is being discussed below, we still have to find an optimal way to do it, as we cannot call `ColorTranslator` from the Code Cracker project and see if it throws, as CC is a PCL, and `System.Drawing` is not available.

@dgmachado is working on it.

### PR DESCRIPTION
**Pull request by dgmachado**
Corrected ValidateColorAnalyzer:
   .Used LocalizableString
   .Used IsKind for faster checking types
   .Fixed the low code coverage

### CODE REVIEW

**Comment by giggio** [comment]
@dgmachado Why did you close this? Is this an update to #435?

**Comment by giggio** [comment]
BTW, it seems you need to rebase your changes.

**Comment by dgmachado** [comment]
When I tried to push the code to the code-cracker repository the github warned as following:

image

And look at this:

image

I think i need to rebase to vnext repository instead the master repository. Is this the right solution?

**Comment by giggio** [comment]
OMG... This is a mess. As your change is very specific to a few files, I would simply copy the files somewhere (backup) and reset everything.
So, basically:
* Copy your analyzer and code fixes files (I am assuming you did not change any of the other files)
* `git checkout master`
* `git branch -D ValidatingColor`
* `git reset --hard origin/master`
* `git pull code-cracker master`
* `git checkout vnext`
* `git reset --hard origin/vnext`
* `git pull code-cracker vnext`
* `git checkout -b ValidatingColor`
* Copy your files back, commit, and `git push origin ValidatingColor --force`
* Close this PR, open a new one.

Never merge back changes from the other branches, always rebase.
If you speak portuguese, try reading this: http://blog.lambda3.com.br/2015/06/trabalhando-com-o-github-e-o-codecracker/

**Comment by dgmachado** [comment]
Thank you man for your patience and your help. I pushed another PR.

**Comment by dgmachado** [comment]
I'm brazilian and I read your post. It is an excellent step by step Guide. Thank you again.

**Comment by AlbertoMonteiro** [comment]
@dgmachado @giggio FTW!!!

**Pull request closed without merging**
