### PR TITLE
Change foreach to linq

### LINKED ISSUE #22: Convert loop to linq expression
We will start with simple ones, looking into foreach and a simple if:

This:

````csharp
var peopleNames = new List<string>();
foreach (var person in people)
{
    peopleNames.Add(person.Name);
}
````

Becomes:

````csharp
var peopleNames = from person in people
                  select person.Name;
````

And this:

````csharp
var peopleNames = new List<string>();
foreach (var person in people)
{
    if (person.Id > 3)
        peopleNames.Add(person.Name);
}
````

Becomes:

````csharp
var peopleNames = from person in people
                  where person.Id > 3
                  select person.Name;
````

Diagnostic id: `CC0050`
Category: `Refactoring`
Severity: `Hidden`

### PR DESCRIPTION
**Pull request by giggio**
Closes #22

### CODE REVIEW

**Comment by giggio** [comment]
@carloscds Can you check this out, pls?

**Comment by carloscds** [comment]
@giggio I will.

**Comment by carloscds** [comment]
@giggio I can't merge it. Can you check ?

**Comment by giggio** [comment]
@carloscds I had just accepted another PR and that created a confict. I just rebased it now.

**Pull request merged**
