### PR TITLE
add property to constructor #307

### PR DESCRIPTION
**Pull request by julianosaless**
New feature #307

### CODE REVIEW

**Comment by carloscds** [comment]
@julianosaless When I have many properties and choose Document option at fixer, only one property is included in constructor. You need to implement FixAllProvider, to correct all properties at same time, if user needs.

**Comment by julianosaless** [comment]
@carloscds, I added the FixAllProvider :)

**Comment by carloscds** [comment]
@julianosaless Can you check your tests, because I have a decrease um code coverage,

**Comment by julianosaless** [comment]
@carlos  i think that probleam will be resolved with this new  comit

**Comment by carloscds** [comment]
Good job @julianosaless

**Comment by julianosaless** [comment]
thank you so much @carloscds.

**Pull request merged**
