### PR TITLE
Change Count() to Count

### LINKED ISSUE #489: Prefer "Count" to "Count()"
If it is an `IList` or some other object that has `Count` as a property, don't use the Linq extension method.

So this:

````csharp
var count = myList.Count();
````

Becomes:

````csharp
var count = myList.Count;
````

**Important**:
`Count` and `Count()` have to return the same type.
`Count()` has to be an extension method.

Diagnostic id: `CC0098`
Severity: Warning
Category: Performance

### PR DESCRIPTION
**Pull request by carloscds**
Fix #489.

### CODE REVIEW

**Comment by giggio** [comment]
@carloscds The PR is fine, but I caught a bug. If you apply the code fix here it will create a compile error:

````csharp
class Program
{
    static void Main(string[] args)
    {
        var b = new Bar();
        Foo(b.Count());
    }
    static void Foo(int i)
    {
    }

    class Bar : List<int>
    {
        public string Count { get; set; }
    }
}
````

You need to check that the property and method have the same return type.

**Comment by carloscds** [comment]
@giggio Bug fixed.

**Comment by giggio** [comment]
@carloscds now failing for this, throwing nullreferenceexception:

````csharp
class Program
{
    static void Main(string[] args)
    {
        var b = new Bar();
        Foo(b.Count());
    }
    static void Foo(int i)
    {
    }

    class Bar : List<int>
    {
        public string Count;
    }
}
````

**Comment by carloscds** [comment]
@giggio Fixed again!

**Pull request merged**
