### PR TITLE
Fix 'Remove Unnecessary ToString in String Concatenation'

### LINKED ISSUE #753: Remove Unnecessary ToString in String Concatenation
The runtime automatically calls `ToString` for string concatenation operations.

For instance, the `ToString` is unnecessary in the following code:

````csharp
 var foo = "a" + new object().ToString();
````

It should become:

````csharp
 var foo = "a" + new object();
````

Should also mark the `.ToString()` invocation with `WellKnownDiagnosticTags.Unnecessary`.

Category: `Style`
Diagnostic Id: `CC0118`
Severity: `Info`

### PR DESCRIPTION
**Pull request by lazarofl**
Fixes #753 

cc0118

### CODE REVIEW

**Comment by giggio** [comment]
@lazarofl Tks! A few things to improve:
* squash the commits
* use the globalized version of the messages, see the NameOf analyzer and fix that use the `LocalizableString` and `Resource` classes.
* we will not pull into the `master` branch. Fork from and pull into the `vnext` branch. You probably will have to rebase. I suggest you first squash, then rebase to another branch.
* you need to write tests for the code fix.

**Comment by lazarofl** [comment]
nice, I'm closing this PR to change the branch

**Comment by giggio** [comment]
@lazarofl are you sending another PR for this one?

**Comment by lazarofl** [comment]
Yes . I had forgot to send :disappointed:

I'll do it until the middle of the week.

**Pull request closed without merging**
