### PR TITLE
CC0056 Identify invalid format strings

### PR DESCRIPTION
**Pull request by thorgeirk11**
Discussed in #335, I have extended the StringFormatArgsAnalyzer to also identify invalid format strings.

### CODE REVIEW

**Comment by giggio** [comment]
@thorgeirk11  I just overviewed the code, it looks good, and tests pass, and coverage increased (yey!). I will have to try it and if everything is ok I will merge.

**Comment by thorgeirk11** [comment]
Awesome.

**Comment by thorgeirk11** [comment]
Woops, did not mean that to happen

**Comment by giggio** [comment]
I have merged it but as the update works perfectly. I am just not sure that we should be using 2 different messages with the same diagnostic id. I am thinking we should use a different id.
@code-cracker/owners please see that we have two rules with the same diagnostic id and different messages:
https://github.com/code-cracker/code-cracker/blob/master/src/CSharp/CodeCracker/Usage/StringFormatArgsAnalyzer.cs#L20-L38
**Note:** Do you think that is ok or should we create a new id? I am leaning towards creating a new one.
There is no fix for the diagnostic generated by `StringFormatArgsAnalyzer`, so the impact would be minimal.

**Comment by carloscds** [comment]
@giggio About this analyzer in particular, I guess that is not a problem.

**Pull request merged**
