### PR TITLE
Add PreferAnyToCountGreaterThanZero Analyzer, closes #490

### LINKED ISSUE #490: Prefer "Any" to "Count() > 0"
If you find a call to `Count() > 0` and the object supports `Any()`, change it `Any()`.
If you find a call to `Count(predicate) > 0` and the object supports `Any(<predicate type>)`, change it `Any(predicate)`.

So this:

````csharp
var any = myEnumerable.Count() > 0;
````

Becomes:

````csharp
var any = myEnumerable.Any();
````

And:

````csharp
var any = myEnumerable.Count(i => i > 3) > 0;
````

Becomes:

````csharp
var any = myEnumerable.Any(i => i > 3);
````

Diagnostic id: `CC0099`
Severity: Information
Category: Style

### PR DESCRIPTION
**Pull request by akamud**
Implemented this code fix for `Count() > 0` and `Count > 0` in C# and VB

### CODE REVIEW

**Comment by giggio** [comment]
@akamud It is accepting `xs.Count() > 1`. It should only work with `> 0`. Please fix that on VB and C#.
Also, I noticed you are not using the Count Property, on the method invocation. I know it was not specified on #490, but I think it makes sense to have it as well, what do you think? Can you add it?

**Comment by akamud** [comment]
Oops, forgot to check for 0 only.

I actually skipped Count (property) because of [this analyzer](https://github.com/code-cracker/code-cracker/issues/489) that is being implemented. What do you think, is Any() better than Count > 0?

**Comment by giggio** [comment]
@akamud I think you can still do `Count`, even though #489 is there.
I noticed that for a Collection, Any is slightly inefficient than checking the count. See:
Any:
https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Enumerable.cs#L1874
Count:
https://github.com/dotnet/corefx/blob/master/src/System.Linq/src/System/Linq/Enumerable.cs#L1905
In `Any` it always gets the enumerator, and then it enumerates. That is more expensive than checking for `Count`. But the readability of `Count` is better. And `Count()` is special cased to deal with collections.
Anyway, I'd offer it to both `Count()` and `Count`.

**Comment by akamud** [comment]
I fixed the C# and VB analyzers and rebased.  
Anything else missing?

**Comment by giggio** [comment]
@akamud Got a few conditions that needed fixing and fixed them. Check out 80c14a1.

**Comment by akamud** [comment]
Thanks @giggio :+1:

**Pull request merged**
