### PR TITLE
Fixes to RemoveAtFromVariablesAnalyzer

### PR DESCRIPTION
**Pull request by thdotnet**
I've fixed the points identified during the Code Review. Please check this new PR.

### CODE REVIEW

**Comment by carloscds** [comment]
@thdotnet Did you create a new PR ? Because I can't see @giggio CodeReviews!

**Comment by thdotnet** [comment]
@carloscds  Yes, I'm sorry. I'll link the previous one.

https://github.com/code-cracker/code-cracker/pull/840#event-808067896

**Comment by carloscds** [comment]
@thdotnet Thiago, this file in your GitHub repo is different from file in PR: 
Your repo: https://github.com/thdotnet/code-cracker/blob/master/src/CSharp/CodeCracker/Style/RemoveAtFromVariablesAnalyzer.cs 

Can you check please ?

**Comment by thdotnet** [comment]
@carloscds Are you sure? I was looking the content, they are the same:

Mine:
https://github.com/thdotnet/code-cracker/blob/b95b7b8b7890e65b6c7902b5be352c697bdc0321/src/CSharp/CodeCracker/Style/RemoveAtFromVariablesAnalyzer.cs

Commit:
https://github.com/code-cracker/code-cracker/pull/845/files

**Comment by carloscds** [comment]
@thdotnet Now it's ok, maybe a cache here.

**Comment by carloscds** [comment]
@thdotnet On this sample code, analyzer will be fired twice:
image
can you check ?

**Comment by thdotnet** [comment]
From the point of view of code, they are different statements: declaration and increment. @giggio said that not only declarations should be included in this Analyzer, that's why it's launching twice. Do you have an idea how to "solve" that? Is that a bug?

**Comment by carloscds** [comment]
@giggio What do you think ?

**Comment by carloscds** [comment]
@thdotnet Please, fix duplicate message of this analyzer. It need to show only one message.

**Comment by thdotnet** [comment]
@carloscds as I said, it won't work the way @giggio  said. I can turn back to the previous solution which will cover most of declarations...

**Comment by carloscds** [comment]
@thdotnet I'm waiting for @giggio considerations. But IMHO, analyzer can't show same message twice.

**Comment by giggio** [comment]
It is not only on variable declarations, but field declarations, or anywhere else the `@` can be used.
For example, all `@` should be removed:

````csharp
namespace @ConsoleApplication3
{
    class @Program
    {
        private string @b;
        public event EventHandler @e;
        static void Main(string[] args)
        {
            var @a = "";
        }
        public void @Foo()
        {
        }
        public int @MyProperty { get; set; }
    }
}
````

**Comment by giggio** [comment]
The changes I requested on #840 are fine. I see there are conflicts in the current code. I haven't reviewed it again now.

**Comment by carloscds** [comment]
@giggio For you this PR it's ok ?

**Comment by thdotnet** [comment]
I agree with you @carloscds, it should raise only one message. I'll spend more time trying to achieve that. Sorry, I'm still learning Roslyn + many other things :P

**Comment by giggio** [comment]
@thdotnet how is this coming?

**Comment by thdotnet** [comment]
@giggio As CDS reported before, it's raising duplicate error messages. I've spent a few time trying to fix that but with no success

**Comment by giggio** [comment]
Ok, I am closing the PR, if you want to restart it let us know.

**Pull request closed without merging**
