### PR TITLE
Remove unused parameters: analyzer and fix

### LINKED ISSUE #24: Remove unused parameters
This:

````csharp
int Foo(int a, int b)
{
    return a;
}
````

Becomes:

````csharp
int Foo(int a)
{
    return a;
}
````

Don't offer a diagnostic if:

* The method is an interface implementation or an override.
* It is a constructor on a serializable object (see pattern [here](http://msdn.microsoft.com/en-us/library/ms973893.aspx)).
* It is an event handler (`object` and then an `EventHandler`).

This is a `Warning`, Category `Usage`.
Diagnostic id: `CC0057`

### PR DESCRIPTION
**Pull request by giggio**
Fixes #24.

image

### CODE REVIEW

**Comment by giggio** [comment]
Build is passing: https://ci.appveyor.com/project/code-cracker/code-cracker/build/1.0.0.264

**Comment by viniciushana** [comment]
Looks good!

**Comment by carloscds** [comment]
@viniciushana Are you working in this PR ?

**Comment by viniciushana** [comment]
Not really, just did a quick glance over the changes.

**Comment by carloscds** [comment]
ok. I will go analyze it.

**Comment by carloscds** [comment]
@giggio If I have a call to method that has unused parameter and I apply this, my code broken:
````csharp
 static void Main(string[] args)
        {
            foo(10, 20);
           
        }

        public static void foo(int a, int b)
        {
            int c = a;

        }
````
Do you expect to check this ?

**Comment by viniciushana** [comment]
And then again we reach a point where we need to fix references done throughout the whole codebase :(

**Comment by giggio** [comment]
@carloscds another one of those problems of referenced code, that may be anywhere on the solution. Good catch, Carlos! But I don't know what to do... I think, from what we discussed earlier this week on our meeting, that we can make the change and let it break, but I am not sure... what do you think. @viniciushana @ElemarJR what do you think?

**Comment by carloscds** [comment]
@giggio It´s same case of privateset, maybe change to hidden and not warning.

**Comment by giggio** [comment]
@carloscds I think I found a solution. As we are going to remove the parameter, I can do that on the code fix, and that can be async. Hold on, I will fix it, I will send an update.

**Comment by giggio** [comment]
@carloscds this was fixed. Reference is now updated. Beautiful! :bicyclist:
@ElemarJR Check out the code fix, I think you will like it.

**Comment by giggio** [comment]
Build is passing: https://ci.appveyor.com/project/code-cracker/code-cracker

**Comment by giggio** [comment]
Build is passing: https://ci.appveyor.com/project/code-cracker/code-cracker/build/1.0.0.304

**Comment by carloscds** [comment]
@giggio  Cool.

**Comment by carloscds** [comment]
@giggio Can I merge it ?

**Comment by giggio** [comment]
@carloscds Yes, you can

**Pull request merged**
