### PR TITLE
Fix nested interpolations

### LINKED ISSUE #690: Bug: CC0048 nested interpolations doesn't fix in one iteration
Hi.
When I have nested string.Format , then applying CC0048 will only solve first or selected one of them.
For example on this code:
```c#
var foo = string.Format( "{0}", string.Format( "{0}", 1 ) );
```
It will fix only one of them in one go. I think it would be good to solve them all at once.

Edit: Sorry I forgot to mention by using FixAll in Solution it will only fix one of them instead of both. 
When those string.Formats are concatenated they are fixed correctly. Like in here:
```c#
var foo = string.Format( "{0}", 1 ) + string.Format( "{0}", 1 );
```

### PR DESCRIPTION
**Pull request by giggio**
Closes #690

### CODE REVIEW

**Comment by carloscds** [comment]
@giggio Fix is correcting only one String.Format() each time. Is it correct ?

**Comment by giggio** [comment]
@carloscds The fix all should be fixing all of them. The simple fix will fix only one, or the other.

**Comment by carloscds** [comment]
@giggio Not fix all, only fix. When I click to fix, only first segment is fixed. Is it expect result ?

**Comment by giggio** [comment]
@carloscds yes.

**Pull request merged**
