### PR TITLE
Base classes

### PR DESCRIPTION
**Pull request by giggio**
Related to #214

This is only a start so we can discuss. Please **don't accept the PR** until we are finished discussing.
@ElemarJR @viniciushana @carloscds I need your feedback on this work on base classes.

### CODE REVIEW

**Comment by carloscds** [comment]
I think that this approach will be left more complex to begninners create analyzers.

**Comment by carloscds** [comment]
I didn´t agree with this approache, it´s not necessary create bases classes to create analyzers. Keep simplicity!

**Comment by giggio** [comment]
@code-cracker/owners I have discussed the issue with @carloscds and we agreed that the enum to hold the diagnostic ids is a good idea. I will go ahead and implement that.
We still need to discuss the rest. Let's schedule a meting and decide what we will do.

**Comment by carloscds** [comment]
@code-cracker/owners Great! Let me know if you need help.

**Comment by codecrackerbuild** [comment]
Teste

**Comment by giggio** [comment]
We can't find any more things from this PR to bring to CC.
We see too much complexity on creating a class hierarchy at the moment. We prefer to keep it simple.

**Pull request closed without merging**
