### PR TITLE
Issue #382

### PR DESCRIPTION
**Pull request by carloscds**
Fix issue #382

### CODE REVIEW

**Comment by giggio** [comment]
@carloscds You need to use resources. See the nameof analyzer and fix.

**Comment by giggio** [comment]
@carloscds 

A few issues:

Analyzer does not work if classes are not inside of a namespace.

This code will have several problems:

````csharp
using System;
namespace ConsoleApplication3
{
    using System.Threading.Tasks;

    public class Class1
    {
        DateTime? D() => null;
        async Task Go() { }
    }
    public class Class2
    {
        DateTime? D() => null;
        async Task Go()
        { 
        }

    }
}
namespace ConsoleApplication3.Foo
{
    class Class3
    {
    }
    class Class4
    {
    }
}
````

* Class3 anc Class4 will not raise the diagnostic, and I think it is throwing.
* If you extract Class1 or Class2 the `using System.Threading.Tasks;` will be moved on the new file from inside the namespace declaration to the top of the file.

**Comment by carloscds** [comment]
@giggio Do you have a class outsite namespace ?

**Comment by giggio** [comment]
@carloscds A simple test like this will expose the bug:

````csharp
class Class1 { }
class Class2 { }
````

**Comment by carloscds** [comment]
@giggio My question is: is there a project that has a class outside namespace ?

**Comment by giggio** [comment]
@carloscds I have seen code like this. I don't think it is a good idea to ignore. It would be better to use the compilation root as the base, not the namespace. What do you think?

**Comment by carloscds** [comment]
@giggio For now I think that's ok. Maybe we can improve it in future.

**Comment by giggio** [comment]
There are other errors, did you see?

**Comment by carloscds** [comment]
@giggio I update my PR, did you see ?

**Comment by carloscds** [comment]
@giggio PR updated!

**Comment by giggio** [comment]
@carloscds Still not working with classes under different namespaces. Needs to update analyzer.

**Comment by carloscds** [comment]
@giggio It's working fine. I have tested with two separate namespaces.

**Comment by giggio** [comment]
Now it is perfect!

**Pull request merged**
