### PR TITLE
fixes - #188 - Validate IPAddress.Parse from System.Net

### PR DESCRIPTION
**Pull request by andrecarlucci**
MethodChecker <3

### CODE REVIEW

**Comment by viniciushana** [comment]
Looks great and build passes, thank you!
However, I'm missing two things and I'd like to know your thoughts on them:

- IPv6 is also supported in `IPAddress.Parse`, it'd be nice to have some tests on this
- `IPAddress.Parse` understands strings partly formatted, e.g. translating `20.2` to `20.0.0.2` and `65536` to `0.0.255.255`

**Comment by andrecarlucci** [comment]
I thought about adding those tests at the time but I didn't because that would mean testing the IPAddress.Parse (Microsoft's job :) and not our Analyzer. The Analyzer calls the original method so everything that works there will work for us too.

**Comment by viniciushana** [comment]
Good point! :)

**Comment by paulomorgado** [comment]
Sometimes, the most difficult thing about unit testing is figuring out what the unit is. :smile:

**Pull request merged**
