### PR TITLE
Convert Lambda to Method Group when possible #49

### PR DESCRIPTION
**Pull request by sqdavid**
Replace a simple lambda expression that only invokes a method that has a
compatible signature with the method itself

### CODE REVIEW

**Comment by hpshelton** [comment]
"ConvertLambdaExpressionToMethodGroupAnalizer.cs" should instead be named "ConvertLambdaExpressionToMethodGroupAnalyzer.cs". Be sure to update the class name as well.

**Comment by giggio** [comment]
@hpshelton agreed. @sqdavid, please update.
Also, @sqdavid, would you please squash the commits? I am not sure how well you know git, so just to help: you do it like that: `git rebase -i master`. Be careful because you may end up messing up the commits, so check everything before you `git push --force` it.

**Comment by sqdavid** [comment]
updated the class name.

**Comment by giggio** [comment]
@sqdavid it is merged. I removed the unnecessary check happening on the code fix provider. You were already checking that on the speculative model, you did not need to check it again. All tests are passing. If that code was necessary we need a test to show it. Look at ee728b6 to see the changes.

**Comment by sqdavid** [comment]
Great! I think the removed check was not needed

**Pull request merged**
