### PR TITLE
Vb usage unused parameter

### PR DESCRIPTION
**Pull request by jwooley**
Fixes https://github.com/code-cracker/code-cracker/issues/291

### CODE REVIEW

**Comment by carloscds** [comment]
@jwooley Did you check code commented in #291 ?

**Comment by jwooley** [comment]
@carloscds Added unit test specific to check issue #291 . Test passed with the previously submitted PR. Removed #pragma directive in the analyzer.

**Comment by carloscds** [comment]
@jwooley I have saw that you add many c# tests, but you add same tests in vb ?

**Comment by carloscds** [comment]
@jwooley Hi Jim, do you have some news about this ?

**Pull request merged**
