### PR TITLE
Fix `nameof` fix to work correctly with methods with non system types

### LINKED ISSUE #594: Suggested Nameof fix incorrectly suggests wrong type
The following code fragment 

        public ActionResult ChangePassword(ChangePasswordMessageId? message, bool? Redirect = false)
        {
            var returnUrl = "ChangePassword";

Correctly identifies a place where `nameof` should be used. However it suggests using `nameof(ChangePasswordMessageID)` instead of the correct `nameof(ChangePassword)`. If I change the type of `message` it produces the correct fix, and if I change `returnUrl` to `"ChangePasswordMessage"` then it does not suggest any fix. This leads me to believe that it's correctly identifying the issue, but incorrectly finding the suggested fix because of the matching prefix, although I haven't looked at the code so I can't be sure (I'll take a look later on if you want).

Tested with code-cracker version 1.0.0-rc2 (although I believe it also existed in earlier versions).

Here is a simple test that will not work:

````csharp
public class TypeName
{
    void Foo(TypeName d)
    {
        var bar = new [] { "Foo" };
    }
}
````

And here is the test case:

````csharp
        [Fact]
        public async Task ReplacesUsingMethodName()
        {
            const string source = @"
public class TypeName
{
    void Foo(TypeName d)
    {
        var bar = new [] { ""Foo"" };
    }
}";

            const string fixtest = @"
public class TypeName
{
    void Foo(TypeName d)
    {
        var bar = new [] { nameof(Foo) };
    }
}";
            await VerifyCSharpFixAsync(source, fixtest);
        }
````

@mirhagk is working on it.

### PR DESCRIPTION
**Pull request by mirhagk**
Fixes #594

### CODE REVIEW

**Comment by giggio** [comment]
@mirhagk This will not fix the bug. Here is a simple test that will not work:

````csharp
public class TypeName
{
    void Foo(TypeName d)
    {
        var bar = new [] { "Foo" };
    }
}
````

And here is the test case:

````csharp
        [Fact]
        public async Task ReplacesUsingMethodName()
        {
            const string source = @"
public class TypeName
{
    void Foo(TypeName d)
    {
        var bar = new [] { ""Foo"" };
    }
}";

            const string fixtest = @"
public class TypeName
{
    void Foo(TypeName d)
    {
        var bar = new [] { nameof(Foo) };
    }
}";
            await VerifyCSharpFixAsync(source, fixtest);
        }
````

**Comment by giggio** [comment]
@mirhagk Are you looking into this?

**Comment by giggio** [comment]
@mirhagk It is ok if you don't have time to fix this, but in that case we will make it up for grabs again. Only if we don't hear from you, ok?

**Comment by mirhagk** [comment]
Hey sorry, got busy the last week, I should have time to fix it over the next few days

**Comment by mirhagk** [comment]
Okay I've fixed that test case as well (I had only put it on the analyzer, and not on the code fix provider)

**Pull request merged**
