### PR TITLE
CS0060 and CS0061 Inconsistent accessibility code fix

### PR DESCRIPTION
**Pull request by baks**
Fixes `CS0060` and `CS0061` in #381.

Implementation with tests for `CS0060` and `CS0061` inconsistent accessibility compiler errors.

It looks like we finally have fix for every compiler error related to inconsistent accessibility :smiley:

### CODE REVIEW

**Comment by giggio** [comment]
@baks I caught an interesting bug. If you have this code:

````csharp
class Program
{
    static void Main(string[] args)
    {
    }
}
public class Foo
{
    protected class Bar : Program
    {
    }
}
````

If you apply the fix from the `Bar` class, the `Program` class will become `protected`, and that would be illegal. It should be `public`.

**Comment by baks** [comment]
@giggio, thank you for catching this. I've fixed it.

Also I've made small refactoring in class/method names, files location.

**Comment by giggio** [comment]
@baks Would you pleas fix the conflicts?

**Comment by baks** [comment]
@giggio, thank you for notifying me. I didn't notice that the conflicts have arisen.

**Pull request merged**
