### PR TITLE
Solving bug for csharp impl #290

### PR DESCRIPTION
**Pull request by ElemarJR**
I would like to check if this is enough. So, I will do that in VB.

### CODE REVIEW

**Comment by carloscds** [comment]
@ElemarJR Elemar, This code call fixer, but I have a call to method in a partial class:

''''csharp
public partial class foo
    {
        public foo()
        {

        }

        private void test()
        {
        }
    }

    public partial class foo
    {
        public void test2()
        {
            test();
        }
    }
''''

**Comment by ElemarJR** [comment]
I wrote a test with this scenario. Are you sure?

**Comment by ElemarJR** [comment]
I just added another test with the specific scenario proposed by you... passing.

**Comment by carloscds** [comment]
@ElemarJR Ok, but in this case, fixer shouldn´t remove method, right ?

**Comment by ElemarJR** [comment]
@carloscds fixer will never be invoked if the diagnostic does not reports it. Am I right?

**Comment by giggio** [comment]
:+1:

**Comment by giggio** [comment]
C# is done. Now VB! :D

**Pull request merged**
