### PR TITLE
Bug fix cc0091 not working when used with delegates

### PR DESCRIPTION
**Pull request by martinzimmermann**
When a Method, that should be made static is used somewhere like `new  X().MethodToBecomeStatic();`. I fix it to `new X(); X.MethodToBecomeStatic()` to ensure that the program logic is not broken.

### CODE REVIEW

**Comment by jwooley** [comment]
If it is a static method, it should not be called on the type, not the instance. It should be changed to 

T.MethodToBecomeStatic() where T is the type of X.

**Comment by martinzimmermann** [comment]
Yes, this is done, but the constructor call is preserved. 

What I mean with this code:
```csharp
using System;
namespace ConsoleApplication1
{
    class Type1
    {
        public static bool Initialized = false;
        private int i;
        public Type1()
        {
            i = 0;
            Initialized = true;
        }
        public bool Foo()
        {
            return Initialized;
        }
    }
    class Type2
    {
        private int i = 0;
        public void Bar() {
            i++;
            var a = new Type1().Foo();  // <- original, should be refactored
            Console.WriteLine(a ? ""Initialized"" : ""Not Initialized""); //  <- this prints "Initialized"
        }
    }
}
```
my fix would add a `new Type1();` as a new statement and replace the original `new Type1()` with `Type1` so the code refactors to this:
```csharp
using System;
namespace ConsoleApplication1
{
    class Type1
    {
        public static bool Initialized = false;
        private int i;
        public Type1()
        {
            i = 0;
            Initialized = true;
        }
        public static bool Foo()
        {
            return Initialized;
        }
    }
    class Type2
    {
        private int i = 0;
        public void Bar() {
            i++;
            new Type1();  // <- this is added
            var a = Type1.Foo();  // <- new Type1() is replaced with Type1
            Console.WriteLine(a ? "Initialized" : "Not Initialized");  //  <- this prints "Initialized"
        }
    }
}
```
instead of just replacing the `new Type1()` with `Type1 `:
```csharp
using System;
namespace ConsoleApplication1
{
    class Type1
    {
        public static bool Initialized = false;
        private int i;
        public Type1()
        {
            i = 0;
            Initialized = true;
        }
        public static bool Foo()
        {
            return Initialized;
        }
    }
    class Type2
    {
        private int i = 0;
        public void Bar() {
            i++;
            var a = Type1.Foo();  // <- only new Type1() is replaced with Type1
            Console.WriteLine(a ? "Initialized" : "Not Initialized");  //  <- this prints "Not Initialized"
        }
    }
}
```
In this example you can see that the original code would print "Initialized". 
The first fix, with the `new Type1()`; inserted would also print "Initialized".
The second fix without the `new Type1();` would print "Not Initialized".

I think that fixes shouldn't change the behavior of the code, so I would prefer the first fix.
But if you want to have the second fix I can also change the code so that no constructor call is added.

**Comment by giggio** [comment]
PR #691 is fixing this, along with several other problems on `CC0091`. I was working on it from issue #680. It conflict with this one.
@martinzimmermann I also noticed you commented on #680. When you want to start working on an issue, please check if there isn't somebody already working on it. The first one assigned will have priority. This is explaining on the contributing doc, so we don't have 2 or more people working on the same issue.
Also, I am not sure we should keep the constructor call. #691 is not keeping it. I understand the collateral effects of a constructor call, but there shouldn't be any, besides the object construction itself, it is bad design. I believe that the most common use case would be to not keep it. But I understand some people might want to keep it.
We could offer to code actions for this scenario. But maybe this is too much. @code-cracker/owners what do you think?

**Comment by martinzimmermann** [comment]
@giggio: I’m very sorry for the inconvenience. I was initially fixing #677 this fix also accidentally has fixed #680, much like PR #691 also fixes #677.
Anyway thanks for the feedback, next time I will be more careful.

**Pull request closed without merging**
