### PR TITLE
Return task instead of await

### PR DESCRIPTION
**Pull request by thorgeirk11**
This PR introduces the ReturnTaskInsteadOfAwaitAnalyzer.
Discussed in #151. 
I also added 26 Unit tests to cover both the analyzer and CodeFix. 

Please let me know what you think :)

### CODE REVIEW

**Comment by giggio** [comment]
@thorgeirk11 Looks pretty good. But you are not using the resources for globalization. Check out `NameOfAnalyzer` and code fix for an example.

**Comment by thorgeirk11** [comment]
@giggio Ah thanks, I wasn't sure how to use it. 
I have pushed a fix for that, so now it uses the resources correctly. :+1:

**Comment by giggio** [comment]
@thorgeirk11 I am getting a null reference exception on this code:

````csharp
        public static async Task FooAsync()
        {
            await Task.Delay(0);
        }
````

**Comment by thorgeirk11** [comment]
Will look into it when I get home ! :+1:

**Comment by thorgeirk11** [comment]
This seems to work in a unit test. Could I be missing something ?
image

**Comment by giggio** [comment]
@thorgeirk11 I am not sure why I got that problem. I reset the Rolsyn VS instance and the problem went away.

**Comment by giggio** [comment]
@thorgeirk11 Actually, I got the problem to show up again. It does not show on your test because it only triggered on incomplete methods, the problem was that `methodDecl.Body` was null while the user typed.
This would trigger it:

````csharp
public static async Task FooAsync()
````

(without the body)

Also, on your test, you are not wrapping the method on a class/struct, so there would be other C# errors. This happened on other tests of yours.

It is a simple fix, I fixed it myself on f4b15d4. Also see the other small changes I did.

**Pull request merged**
