### PR TITLE
Convert method to property

### PR DESCRIPTION
**Pull request by Shiney**
Created analyzer and code fix provider for convert to property.

It doesn't support virtual or abstract methods or interfaces. #508

### CODE REVIEW

**Comment by giggio** [comment]
@Shiney Please update the analyzer and code fix to use localizable strings for title, etc. See the `nameofanalyzer` and fix for an example.

**Comment by giggio** [comment]
@Shiney This is raising a diagnostic, and it shouldn't. If the code fix is applied it will create a compiler error:

````
class C
{
    public int I(string i) => 1;
    public int I() => 1;
}
````

**Comment by Shiney** [comment]
@giggio if I put that code into a test and call 
```CSharp
            await VerifyCSharpHasNoDiagnosticsAsync(test);
```

Then the test passes. Do you have any idea what I've done wrong in the test?

**Comment by giggio** [comment]
I have no idea why. Have you tried running? I get the problem there, see:

error

**Comment by giggio** [comment]
I noticed that this is not coming from us. Maybe from VS/Roslyn directly?
So, anyway, disregard, I will check the rest.

**Comment by giggio** [comment]
@Shiney I have found a problem when the class is implementing an interface or inheriting from a base class. It's methods are being changed without change the base class or interface.

So, here, changing `I` to become a property on `Foo` should also change the interface and `Foo2`. Same thing for the `Virtual` and `Abstract` methods.

````csharp
abstract class BaseFoo
{
    public abstract int Abstract();
    public virtual int Virtual()
    {
        throw new NotImplementedException();
    }
}
interface IFoo
{
    int I();
}
class Foo : IFoo
{
    public int I()
    {
        throw new NotImplementedException();
    }
}
class Foo2 : BaseFoo, IFoo
{
    public override int Abstract()
    {
        throw new NotImplementedException();
    }
    public override int Virtual()
    {
        throw new NotImplementedException();
    }
    public int I()
    {
        throw new NotImplementedException();
    }
}
````

I noticed that Microsoft is also suggesting this fix, but theirs is broken, it suggests to change even when there is an overload. I think they released it with Roslyn 1.1, as I don't think it was there before. I was going to suggest we stop this feature, but since theirs is broken, let's make ours better. :)
Also, as you have to update those items above, I think you should also support virtual or abstract methods, and also interface methods.

**Comment by Shiney** [comment]
Do you think the changing even if there is an overload is bad? It seems to me like that is a less confusing experience for the user as they won't start getting confused when they can't make the change they want to make.

**Comment by giggio** [comment]
We should not offer a change if there is an overload, as that would break the code.

**Comment by Shiney** [comment]
I think we should probably just drop the feature it gets really complicated really fast especially since there are so many different ways of implementing a method. For example if a method with exactly the same signature is a member of two interfaces and you do the convert method to property on one of the interfaces what is supposed to happen when you do the convert method to property? I'm not convinced there's a good story about what the right thing to do is. If theres an out of the box solution it's probably bettter if they just use that.

**Comment by giggio** [comment]
@Shiney yes, there is an out of box solution for that, made by the roslyn team. What do you think, @code-cracker/owners, should we drop it?

**Comment by carloscds** [comment]
@giggio I think that already exsits, we shouldn't develop again!

**Comment by giggio** [comment]
Ok, so feature dropped.

**Pull request closed without merging**
