### PR TITLE
Fixed issue #537 by creating multiple variable declarations rather th…

### PR DESCRIPTION
**Pull request by Shiney**
…an a single declaration.

I added a test for this issue directly, and also added a test that the CodeFix doesn't destroy the trivia.

### CODE REVIEW

**Comment by Shiney** [comment]
#537

**Comment by thorgeirk11** [comment]
I am not sure we can safely use var for this case. See the following example:

```CSharp
class Animal
{
    public string Foo() { return "Animal"; }
}
class Cat : Animal
{
    public new string Foo() { return "Cat"; }
}
class Dog : Animal
{
    public new string Foo() { return "Dog"; }
}
public void Bar()
{
    Animal dog = new Dog(), cat = new Cat();
    Console.WriteLine(dog.Foo()); // Prints out Animal.
    Console.WriteLine(cat.Foo()); // Prints out Animal.
}
```

However when refactored:
```CSharp
public static void Bar()
{
    var dog = new Dog();
    var cat = new Cat();
    Console.WriteLine(dog.Foo()); // Prints out dog.
    Console.WriteLine(cat.Foo()); // Prints out cat.
}
```

What do you think @code-cracker/collaborators ?

**Comment by akamud** [comment]
Indeed. We could check if the left side is a base type of the right side before suggesting `var`.

**Comment by Shiney** [comment]
foreach (var variable in variableDeclaration.Variables)
            {
                if (variable.Initializer == null) return;
                var conversion = semanticModel.ClassifyConversion(variable.Initializer.Value, variableType);
                if (!conversion.IsIdentity) return;
            }

This code is in the analyser and should be stopping that example. I'm on my phone so I have not checked there is a test for that.

Also that issue with the code fix is not related to the multiple declarations. If it's an issue then it would be an issue with single declarations too.

FYI resharper does not seem to support this refactoring on multiple declarations. Maybe it's not that valuable as it increases the number of lines of code.

Thanks for committing this.

**Pull request merged**
