### PR TITLE
throw expression must be inside a catch block

### PR DESCRIPTION
**Pull request by sqdavid**
Targeting BUG on CC0012: RethrowExceptionAnalyzer throwing "Sequence
contains no elements"

### CODE REVIEW

**Comment by sqdavid** [comment]
@giggio @carloscds please verify the PR. I couldn't build corefx in my machine to run CC against it. Anyway, I could identify the source of the exception and added a check.

**Comment by giggio** [comment]
You need to reenable the analyzer. To test corefx run analyzecorefx.ps1 on the test\csharp dir.

**Comment by carloscds** [comment]
@sqdavid Can you enable analyzer and send another PR ?

**Comment by giggio** [comment]
This line: https://github.com/code-cracker/code-cracker/blob/master/src/CSharp/CodeCracker/Usage/RethrowExceptionAnalyzer.cs#L27

**Comment by giggio** [comment]
I am looking into it.

**Comment by giggio** [comment]
Fixed on ed7a833. @sqdavid You got the bug, I ran it on corefx and it is gone.

**Comment by sqdavid** [comment]
great @giggio, and thanks for reenabling it. =)

**Pull request merged**
