### PR TITLE
Remove private method never used

### PR DESCRIPTION
**Pull request by julianosaless**
"RemovePrivateMethodNeverUsedAnalyzer (CC0068) throwing cast exception #276"

### CODE REVIEW

**Comment by codecrackerbuild** [comment]
Build failed! Details: https://ci.appveyor.com/project/code-cracker/code-cracker/build/1.0.0.415

**Comment by codecrackerbuild** [comment]
Build passed! Details: https://ci.appveyor.com/project/code-cracker/code-cracker/build/1.0.0.417

**Comment by giggio** [comment]
@julianosaless It is still throwing. You need to reenable the analyzer (set `isEnabledByDefault: true`), build, and run `.\test\CSharp\AnalyzeCoreFx.ps1`. It will fail with the errors mentioned. At the beginning the script will show you where the solution is in the file system so you search for the error. Here is the latest log:

````
12557   info AnalyzerDriver: The Compiler Analyzer 'CodeCracker.Usage.RemovePrivateMethodNeverUsedAnalyzer' threw an exception with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.StructDeclarationSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax'.'.
41246   info AnalyzerDriver: The Compiler Analyzer 'CodeCracker.Usage.RemovePrivateMethodNeverUsedAnalyzer' threw an exception with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.StructDeclarationSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax'.'.
119249   info AnalyzerDriver: The Compiler Analyzer 'CodeCracker.Usage.RemovePrivateMethodNeverUsedAnalyzer' threw an exception with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.StructDeclarationSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax'.'.
128105   info AnalyzerDriver: The Compiler Analyzer 'CodeCracker.Usage.RemovePrivateMethodNeverUsedAnalyzer' threw an exception with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.StructDeclarationSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax'.'.
130512   info AnalyzerDriver: The Compiler Analyzer 'CodeCracker.Usage.RemovePrivateMethodNeverUsedAnalyzer' threw an exception with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.StructDeclarationSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax'.'.
141006   info AnalyzerDriver: The Compiler Analyzer 'CodeCracker.Usage.RemovePrivateMethodNeverUsedAnalyzer' threw an exception with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.StructDeclarationSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax'.'.
181935   info AnalyzerDriver: The Compiler Analyzer 'CodeCracker.Usage.RemovePrivateMethodNeverUsedAnalyzer' threw an exception with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.StructDeclarationSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax'.'.
183366   info AnalyzerDriver: The Compiler Analyzer 'CodeCracker.Usage.RemovePrivateMethodNeverUsedAnalyzer' threw an exception with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.StructDeclarationSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax'.'.
185033   info AnalyzerDriver: The Compiler Analyzer 'CodeCracker.Usage.RemovePrivateMethodNeverUsedAnalyzer' threw an exception with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.StructDeclarationSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax'.'.
190302   info AnalyzerDriver: The Compiler Analyzer 'CodeCracker.Usage.RemovePrivateMethodNeverUsedAnalyzer' threw an exception with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.StructDeclarationSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax'.'.
````

**Comment by giggio** [comment]
@julianosaless I fixed it.

**Pull request merged**
