### PR TITLE
Vb usage unused parameter

### PR DESCRIPTION
**Pull request by jwooley**
Yet another VB translation

### CODE REVIEW

**Comment by carloscds** [comment]
@jwooley Hi Jim, can you update your project for PR ?

**Comment by jwooley** [comment]
@carloscds Not sure which PR you're referring to.

**Comment by carloscds** [comment]
jwooley  This pull request. You need to update your source repo because Merge button is disabled.

**Comment by giggio** [comment]
@jwooley @carloscds Please disregard the build comment above. I am working with AppVeyor to fix an issue.

**Comment by jwooley** [comment]
Appveyor build error is likely due to an out of sync merge in test.common.codefixverifier that I made in a different branch, but doesn't appear to be in the current build. It's not part of this pull request. Updated source repro merging other VB translation branch changes.

**Comment by giggio** [comment]
@jwooley It is building now. I have fixed the appveyor integration, so we get this nice little feedback from them now, stating the build status.

**Pull request merged**
