### PR TITLE
- Fix #780 - Adding more tests and and solve conflicts 

### LINKED ISSUE #780: CC0120: Suggest default for switch statements (C#)
A lot of bugs are caused by non-exhaustive matching in switch statements.
If there is no default case one should be added that throws an exception.

Before:

``` csharp
switch (a)
{
    case "":
        break;
}
```

After:

``` csharp
switch (a)
{
    case "":
        break;
    default:
        throw new Exception("Unexpected Case");
}
```

Should not raise for `boolean` if `true` and `false` are already handled:

``` csharp
var f = true;
switch (f)
{
    case true:
        break;
    case false:
        break;
    default:
        break;
}
```

Should not raise a diagnostic if [CS0151](https://msdn.microsoft.com/en-us/library/dh0x1stb.aspx)(C# A switch expression or case label must be a bool, char, string, integral, enum, or corresponding nullable type) is already raised in the switch.

Diagnostic Id: `CC0120`
Category: `Design`
Severity: `Warning`

Same as #767, but for C#.

@cezarant is working on it.

### PR DESCRIPTION
**Pull request by cezarant**
Following the suggestions of the developers in the first PR to resolve the issue # 780, this update has tests for situations of Boolean and integer parameters and treatment of exception CS0151.

### CODE REVIEW

**Comment by giggio** [comment]
Found bug #859 on this code. Maybe @cezarant wants to fix it?

**Comment by cezarant** [comment]
Yes, @giggio  I'm already checking.

**Comment by giggio** [comment]
@cezarant I fixed, also there was many refactorings. Check out e1c18b6

**Comment by cezarant** [comment]
Ok @giggio. I will study the refactorings. To learn more about it

**Pull request merged**
