### PR TITLE
Fixes #587 - stripping out non-selected catch blocks. Only remove try…

### LINKED ISSUE #587: Remove empty Catch Block too aggressive
If code has multiple catch blocks in a single try, when selecting the fix to remove empty catch block, it removes all catch blocks not just the one requested. Sample test:

  public void foo()
    {
        try
        {
            Console.WriteLine("foo");
        }
        catch (ArgumentException aex)
        {  
            
                   
        }
        catch 
        {
            throw;
        }
    }

Should return 
  public void foo()
    {
        try
        {
            Console.WriteLine("foo");
        }
        catch 
        {
            throw;
        }
    }

but instead, returns
  public void foo()
    {
        Console.WriteLine("foo");
    }

Is broken in C# and VB

### PR DESCRIPTION
**Pull request by jwooley**
Fixes #587 - stripping out non-selected catch blocks. Only remove try block option if single exception left. Fixes VB and C# implementations.

### CODE REVIEW

**Comment by giggio** [comment]
@jwooley You need to update your code. The current `EmptyCatchBlockCodeFixProvider` is very different, it is already using resources, for example.

**Comment by giggio** [comment]
Hey, @jwooley, can you check this out? ;)

**Comment by giggio** [comment]
@jwooley We can't have warning as errors disabled. What warnings are you seeing?

**Comment by jwooley** [comment]
Responded to your personal email account.

**Comment by jwooley** [comment]
Updated reverting the warnings as errors

**Pull request merged**
