### PR TITLE
Use StringEmpty

### LINKED ISSUE #120: Use String.Empty instead ""
````csharp
var a = "";
````

Becomes 

````csharp
var a = string.Empty;
````

`Style`, `Info`

Diagnostic Id: `CC0084`
Severity: Hidden
Category: Style

### PR DESCRIPTION
**Pull request by carloscds**
Close #120

### CODE REVIEW

**Comment by giggio** [comment]
@carloscds You are analyzing only variable declarations, you should instead be analyzing string literals.
For example, this will not currently raise a diagnostic:

````csharp
void Foo(string s) {}
void Bar()
{
    Foo("");
}
````

But it should.

**Comment by giggio** [comment]
@carloscds I am also not sure if this is an `Info` or a `Refactoring`. This is a such a matter of taste. What do you think. Also, @ElemarJR, you proposed #120, what do you think?

**Comment by carloscds** [comment]
@giggio Look at the test wrote by @ElemarJR. Specification is only about variables.

**Comment by giggio** [comment]
@carloscds it is just an example, it does not mean we should not solve the more generic problem. @ElemarJR do you agree? Carlos, it should not be too hard to change it to a more generic solution.

**Comment by carloscds** [comment]
@giggio Ok. it's make sense. I will implement.

**Comment by giggio** [comment]
@carloscds There were some errors on the fix all, and I also found a problem when using string.empty on attributes, so I excluded them.

**Pull request merged**
