### PR TITLE
Remove unreachable code

### LINKED ISSUE #21: Remove unreachable code
This:

````csharp
void Foo()
{
    return;
    var a = 1; //unreachable
}
````

Will have the `var` line declaration marked as `WellKnownDiagnosticTags.Unnecessary`.
And will become:

````csharp
void Foo()
{
    return;
}
````

Should work for any possible unreachable code, like statements after `throw`, `else` that will never be reached, etc.

Category: `Usage`
Diagnostic id: `CC0055`
Severity: `Info`

### PR DESCRIPTION
**Pull request by giggio**
Closes #21
Also several improvements on the fix all infrastructure verification code.

### CODE REVIEW

**Comment by codecrackerbuild** [comment]
Build failed! Details: https://ci.appveyor.com/project/code-cracker/code-cracker/build/1.0.0.413

**Comment by codecrackerbuild** [comment]
Build failed! Details: https://ci.appveyor.com/project/code-cracker/code-cracker/build/1.0.0.414

**Comment by giggio** [comment]
Build is passing. Coveralls.io is offline and that is failing the build.

**Comment by codecrackerbuild** [comment]
Build passed! Details: https://ci.appveyor.com/project/code-cracker/code-cracker/build/1.0.0.416

**Comment by carloscds** [comment]
Very interesting!

**Pull request merged**
