### PR TITLE
Readme ptbr

### LINKED ISSUE #973: Translate to Portuguese
Could I translate the Read.me file to Portuguese ?

What is the best way to expose it ? link on main read.me ?

### PR DESCRIPTION
**Pull request by carloshenriqueribeiro**
I still do not know how to rebase and square, sorry.
Fixes #973 .

### CODE REVIEW

**Comment by carloscds** [comment]
@carloshenriqueribeiro You can send only readme.md in your PR ?

**Comment by carloshenriqueribeiro** [comment]
@carloscds how can I do this ? the other changes were consequences of the merge with the updated master.

**Comment by carloshenriqueribeiro** [comment]
I'm using VS Code and git by terminal. I followed these instructions.

image

**Comment by carloshenriqueribeiro** [comment]
look my git log on "readme-ptbr" branch.

image

**Pull request closed without merging**
