### PR TITLE
Fix 841

### LINKED ISSUE #841: CC0082: ComputeExpressionCodeFixProvider crashs
# Bug

I dont know if it is a bug or only happens with my setup.

I was playing with your extension and when I open the lamp in any of the next codes:

``` csharp
FooMethod(60 * 2);
string.Format("2 Hours in minutes: {0}", 60 * 2);
```

I got:

bug

I ran VS with devenv.exe /log and I got:

`Não é possível converter um objeto do tipo 'Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentSyntax' no tipo 'Microsoft.CodeAnalysis.CSharp.Syntax.BinaryExpressionSyntax'.
 at CodeCracker.CSharp.Refactoring.ComputeExpressionCodeFixProvider.<ComputeExpressionAsync>d__4.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at CodeCracker.CSharp.Refactoring.ComputeExpressionCodeFixProvider.<RegisterCodeFixesAsync>d__3.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.CodeAnalysis.CodeFixes.CodeFixService.<>c__DisplayClass13_0.<<AppendFixesAsync>b__2>d.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.<PerformFunctionAsync>d__3`1.MoveNext()`

Version: 1.0.1

### PR DESCRIPTION
**Pull request by carloscds**
Fix #841

### CODE REVIEW

**Comment by giggio** [comment]
@carloscds There are conflicts, you used the wrong branch, can you fix that?

**Comment by carloscds** [comment]
@giggio We are using branch 1.0.x ?

**Comment by giggio** [comment]
@carloscds yes.

**Comment by giggio** [comment]
@carloscds can you fix the conflicts so we can integrate this PR?

**Comment by carloscds** [comment]
@giggio Fixed!

**Comment by giggio** [comment]
@carloscds there was problems with the branches, you should had used the correct base one. So I cherry picked your commit into 25b0270b, this PR is not needed anymore, I integrated the code directly.

**Pull request closed without merging**
