### PR TITLE
broken build

### PR DESCRIPTION
**Pull request by sawilde**
I couldn't get the build to work locally until I made the following changes

(the packages.config changes were actually made by VS2015 as it restored the packages)

### CODE REVIEW

**Comment by carloscds** [comment]
@sawilde What version of VS are you using ?

**Comment by sawilde** [comment]
VS2015 CTP6 - however it was on the command line that nuget wouldn't run until I made the chnage to build.targets.ps1

**Comment by carloscds** [comment]
@sawilde What error you receive ? Because I'm running CTP 6 too, without errors

**Comment by sawilde** [comment]
I am prepping a new version of opencover and was checking that the new Mono.Cecil handles the issues that code-cracker raised with the new PDB format and Mono.Cecil

No errors in CTP6 itself - actually the command line

.\Build.ps1 Build

**Comment by sawilde** [comment]
````
Windows PowerShell
Copyright (C) 2014 Microsoft Corporation. All rights reserved.

PS C:\Users\Shaun> cd C:\Projects\external\code-cracker\
PS C:\Projects\external\code-cracker> .\build.ps1
psake version 4.4.1
Copyright (c) 2010-2014 James Kovacs & Contributors

-------------------------[Restore]-------------------------
Restoring C:\Projects\external\code-cracker\CodeCracker.CSharp.sln...
Error: 4/28/2015 10:50:23 PM:
At C:\Projects\external\code-cracker\build.targets.ps1:152 char:5 +     nuget restore $sln +     ~~~~~ [<<==>>] Excepti
on: The term 'nuget' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the s
pelling of the name, or if a path was included, verify that the path is correct and try again.
````

**Comment by carloscds** [comment]
@sawilde Can you try to build using Visual Studio IDE ?

**Comment by sawilde** [comment]
Why? I have no problem with the Visual Studio build.

The problem is with the command line build; as shown above.

**Comment by carloscds** [comment]
@sawilde Even after your changes, simply executing build.ps1 can't restore packages, because you need Nuget Command Line. How do you this test after change ?

**Comment by carloscds** [comment]
@sawilde if you download nuget.exe and restore packages, you can execute build.

**Comment by carloscds** [comment]
@sawilde Your change in build.targets is perfect, but don't need change packages.config.

**Comment by sawilde** [comment]
why not? When I restored packages via VS2015 it automatically updated that file, which when you look at those packages is the right place for them to be registered as they are tools.

**Comment by giggio** [comment]
Both changes make sense to me. It's a weird thing VS never asked me to update packages.config, but I believe this could happen. If we change that, then, the best thing would be to remove it from the Test.Common project where I believe those deps referenced. (I'm away from a computer now)

**Comment by sharwell** [comment]
BTW, if you ever want to make a change where the build works even if the user doesn't have **NuGet.exe** downloaded, feel free to use [this block of code](https://github.com/rackerlabs/dotnet-collections/blob/a970c03a3ac8c9676390343f0381e7d7e491b52b/build/build.ps1#L31-L39) in the build script.

**Comment by sawilde** [comment]
OT: How did you get that coveralls thing to report back?

**Comment by giggio** [comment]
@sawilde I don't know. It just started doing it.

**Pull request merged**
